// Mocks generated by Mockito 5.4.4 from annotations
// in josh_weather/test/infrastructure/datasource/remote_data_source_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i8;

import 'package:dartz/dartz.dart' as _i2;
import 'package:dio/dio.dart' as _i6;
import 'package:event_bus/event_bus.dart' as _i5;
import 'package:internet_connection_checker_plus/internet_connection_checker_plus.dart'
    as _i4;
import 'package:josh_weather/core/core.dart' as _i9;
import 'package:josh_weather/core/module/inject_module.dart' as _i11;
import 'package:josh_weather/feature/infrastructure/datasource/remote/weather_remote_data_source.dart'
    as _i7;
import 'package:josh_weather/feature/infrastructure/model/model.dart' as _i10;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i12;
import 'package:shared_preferences/shared_preferences.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeSharedPreferences_1 extends _i1.SmartFake
    implements _i3.SharedPreferences {
  _FakeSharedPreferences_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeInternetConnection_2 extends _i1.SmartFake
    implements _i4.InternetConnection {
  _FakeInternetConnection_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeEventBus_3 extends _i1.SmartFake implements _i5.EventBus {
  _FakeEventBus_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeDio_4 extends _i1.SmartFake implements _i6.Dio {
  _FakeDio_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [WeatherRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockWeatherRemoteDataSource extends _i1.Mock
    implements _i7.WeatherRemoteDataSource {
  @override
  _i8.Future<
      _i2.Either<_i9.Failure, _i10.CurrentWeatherModel>> getCurrentWeather(
    double? lat,
    double? lng,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getCurrentWeather,
          [
            lat,
            lng,
          ],
        ),
        returnValue:
            _i8.Future<_i2.Either<_i9.Failure, _i10.CurrentWeatherModel>>.value(
                _FakeEither_0<_i9.Failure, _i10.CurrentWeatherModel>(
          this,
          Invocation.method(
            #getCurrentWeather,
            [
              lat,
              lng,
            ],
          ),
        )),
        returnValueForMissingStub:
            _i8.Future<_i2.Either<_i9.Failure, _i10.CurrentWeatherModel>>.value(
                _FakeEither_0<_i9.Failure, _i10.CurrentWeatherModel>(
          this,
          Invocation.method(
            #getCurrentWeather,
            [
              lat,
              lng,
            ],
          ),
        )),
      ) as _i8.Future<_i2.Either<_i9.Failure, _i10.CurrentWeatherModel>>);

  @override
  _i8.Future<
      _i2
      .Either<_i9.Failure, _i10.ForecastWeather3HourModel>> getForecastWeather(
    double? lat,
    double? lng,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getForecastWeather,
          [
            lat,
            lng,
          ],
        ),
        returnValue: _i8.Future<
                _i2.Either<_i9.Failure, _i10.ForecastWeather3HourModel>>.value(
            _FakeEither_0<_i9.Failure, _i10.ForecastWeather3HourModel>(
          this,
          Invocation.method(
            #getForecastWeather,
            [
              lat,
              lng,
            ],
          ),
        )),
        returnValueForMissingStub: _i8.Future<
                _i2.Either<_i9.Failure, _i10.ForecastWeather3HourModel>>.value(
            _FakeEither_0<_i9.Failure, _i10.ForecastWeather3HourModel>(
          this,
          Invocation.method(
            #getForecastWeather,
            [
              lat,
              lng,
            ],
          ),
        )),
      ) as _i8.Future<_i2.Either<_i9.Failure, _i10.ForecastWeather3HourModel>>);

  @override
  _i8.Future<_i2.Either<_i9.Failure, _i10.ForecastWeather3HourModel>>
      getForecastFiveDaysWeather(
    double? lat,
    double? lng,
  ) =>
          (super.noSuchMethod(
            Invocation.method(
              #getForecastFiveDaysWeather,
              [
                lat,
                lng,
              ],
            ),
            returnValue: _i8.Future<
                    _i2
                    .Either<_i9.Failure, _i10.ForecastWeather3HourModel>>.value(
                _FakeEither_0<_i9.Failure, _i10.ForecastWeather3HourModel>(
              this,
              Invocation.method(
                #getForecastFiveDaysWeather,
                [
                  lat,
                  lng,
                ],
              ),
            )),
            returnValueForMissingStub: _i8.Future<
                    _i2
                    .Either<_i9.Failure, _i10.ForecastWeather3HourModel>>.value(
                _FakeEither_0<_i9.Failure, _i10.ForecastWeather3HourModel>(
              this,
              Invocation.method(
                #getForecastFiveDaysWeather,
                [
                  lat,
                  lng,
                ],
              ),
            )),
          ) as _i8
              .Future<_i2.Either<_i9.Failure, _i10.ForecastWeather3HourModel>>);
}

/// A class which mocks [InjectableModule].
///
/// See the documentation for Mockito's code generation for more information.
class MockInjectableModule extends _i1.Mock implements _i11.InjectableModule {
  @override
  _i8.Future<_i3.SharedPreferences> get prefs => (super.noSuchMethod(
        Invocation.getter(#prefs),
        returnValue:
            _i8.Future<_i3.SharedPreferences>.value(_FakeSharedPreferences_1(
          this,
          Invocation.getter(#prefs),
        )),
        returnValueForMissingStub:
            _i8.Future<_i3.SharedPreferences>.value(_FakeSharedPreferences_1(
          this,
          Invocation.getter(#prefs),
        )),
      ) as _i8.Future<_i3.SharedPreferences>);

  @override
  _i4.InternetConnection get internetConnectionChecker => (super.noSuchMethod(
        Invocation.getter(#internetConnectionChecker),
        returnValue: _FakeInternetConnection_2(
          this,
          Invocation.getter(#internetConnectionChecker),
        ),
        returnValueForMissingStub: _FakeInternetConnection_2(
          this,
          Invocation.getter(#internetConnectionChecker),
        ),
      ) as _i4.InternetConnection);

  @override
  String get baseUrl => (super.noSuchMethod(
        Invocation.getter(#baseUrl),
        returnValue: _i12.dummyValue<String>(
          this,
          Invocation.getter(#baseUrl),
        ),
        returnValueForMissingStub: _i12.dummyValue<String>(
          this,
          Invocation.getter(#baseUrl),
        ),
      ) as String);

  @override
  String get apiKey => (super.noSuchMethod(
        Invocation.getter(#apiKey),
        returnValue: _i12.dummyValue<String>(
          this,
          Invocation.getter(#apiKey),
        ),
        returnValueForMissingStub: _i12.dummyValue<String>(
          this,
          Invocation.getter(#apiKey),
        ),
      ) as String);

  @override
  _i5.EventBus get eventBus => (super.noSuchMethod(
        Invocation.getter(#eventBus),
        returnValue: _FakeEventBus_3(
          this,
          Invocation.getter(#eventBus),
        ),
        returnValueForMissingStub: _FakeEventBus_3(
          this,
          Invocation.getter(#eventBus),
        ),
      ) as _i5.EventBus);

  @override
  _i8.Future<_i6.Dio> get authenticatedDio => (super.noSuchMethod(
        Invocation.getter(#authenticatedDio),
        returnValue: _i8.Future<_i6.Dio>.value(_FakeDio_4(
          this,
          Invocation.getter(#authenticatedDio),
        )),
        returnValueForMissingStub: _i8.Future<_i6.Dio>.value(_FakeDio_4(
          this,
          Invocation.getter(#authenticatedDio),
        )),
      ) as _i8.Future<_i6.Dio>);

  @override
  _i6.Dio get publicDio => (super.noSuchMethod(
        Invocation.getter(#publicDio),
        returnValue: _FakeDio_4(
          this,
          Invocation.getter(#publicDio),
        ),
        returnValueForMissingStub: _FakeDio_4(
          this,
          Invocation.getter(#publicDio),
        ),
      ) as _i6.Dio);
}
