// Mocks generated by Mockito 5.4.4 from annotations
// in josh_weather/test/helper/mocks_helper/mocks.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i9;

import 'package:dartz/dartz.dart' as _i2;
import 'package:dio/dio.dart' as _i7;
import 'package:event_bus/event_bus.dart' as _i6;
import 'package:internet_connection_checker_plus/internet_connection_checker_plus.dart'
    as _i4;
import 'package:josh_weather/core/core.dart' as _i5;
import 'package:josh_weather/core/module/inject_module.dart' as _i13;
import 'package:josh_weather/feature/domain/domain.dart' as _i12;
import 'package:josh_weather/feature/infrastructure/datasource/local/my_location_local_data_source.dart'
    as _i11;
import 'package:josh_weather/feature/infrastructure/datasource/remote/weather_remote_data_source.dart'
    as _i8;
import 'package:josh_weather/feature/infrastructure/model/model.dart' as _i10;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i14;
import 'package:shared_preferences/shared_preferences.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeSharedPreferences_1 extends _i1.SmartFake
    implements _i3.SharedPreferences {
  _FakeSharedPreferences_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeInternetConnection_2 extends _i1.SmartFake
    implements _i4.InternetConnection {
  _FakeInternetConnection_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeUrlBuilder_3 extends _i1.SmartFake implements _i5.UrlBuilder {
  _FakeUrlBuilder_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeEventBus_4 extends _i1.SmartFake implements _i6.EventBus {
  _FakeEventBus_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeDio_5 extends _i1.SmartFake implements _i7.Dio {
  _FakeDio_5(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeBaseOptions_6 extends _i1.SmartFake implements _i7.BaseOptions {
  _FakeBaseOptions_6(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeHttpClientAdapter_7 extends _i1.SmartFake
    implements _i7.HttpClientAdapter {
  _FakeHttpClientAdapter_7(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeTransformer_8 extends _i1.SmartFake implements _i7.Transformer {
  _FakeTransformer_8(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeInterceptors_9 extends _i1.SmartFake implements _i7.Interceptors {
  _FakeInterceptors_9(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeResponse_10<T1> extends _i1.SmartFake implements _i7.Response<T1> {
  _FakeResponse_10(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [WeatherRemoteDataSourceIml].
///
/// See the documentation for Mockito's code generation for more information.
class MockWeatherRemoteDataSourceIml extends _i1.Mock
    implements _i8.WeatherRemoteDataSourceIml {
  @override
  _i9.Future<
      _i2.Either<_i5.Failure, _i10.CurrentWeatherModel>> getCurrentWeather(
    double? lat,
    double? lng,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getCurrentWeather,
          [
            lat,
            lng,
          ],
        ),
        returnValue:
            _i9.Future<_i2.Either<_i5.Failure, _i10.CurrentWeatherModel>>.value(
                _FakeEither_0<_i5.Failure, _i10.CurrentWeatherModel>(
          this,
          Invocation.method(
            #getCurrentWeather,
            [
              lat,
              lng,
            ],
          ),
        )),
        returnValueForMissingStub:
            _i9.Future<_i2.Either<_i5.Failure, _i10.CurrentWeatherModel>>.value(
                _FakeEither_0<_i5.Failure, _i10.CurrentWeatherModel>(
          this,
          Invocation.method(
            #getCurrentWeather,
            [
              lat,
              lng,
            ],
          ),
        )),
      ) as _i9.Future<_i2.Either<_i5.Failure, _i10.CurrentWeatherModel>>);

  @override
  _i9.Future<
      _i2
      .Either<_i5.Failure, _i10.ForecastWeather3HourModel>> getForecastWeather(
    double? lat,
    double? lng,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getForecastWeather,
          [
            lat,
            lng,
          ],
        ),
        returnValue: _i9.Future<
                _i2.Either<_i5.Failure, _i10.ForecastWeather3HourModel>>.value(
            _FakeEither_0<_i5.Failure, _i10.ForecastWeather3HourModel>(
          this,
          Invocation.method(
            #getForecastWeather,
            [
              lat,
              lng,
            ],
          ),
        )),
        returnValueForMissingStub: _i9.Future<
                _i2.Either<_i5.Failure, _i10.ForecastWeather3HourModel>>.value(
            _FakeEither_0<_i5.Failure, _i10.ForecastWeather3HourModel>(
          this,
          Invocation.method(
            #getForecastWeather,
            [
              lat,
              lng,
            ],
          ),
        )),
      ) as _i9.Future<_i2.Either<_i5.Failure, _i10.ForecastWeather3HourModel>>);

  @override
  _i9.Future<_i2.Either<_i5.Failure, _i10.ForecastWeather3HourModel>>
      getForecastFiveDaysWeather(
    double? lat,
    double? lng,
  ) =>
          (super.noSuchMethod(
            Invocation.method(
              #getForecastFiveDaysWeather,
              [
                lat,
                lng,
              ],
            ),
            returnValue: _i9.Future<
                    _i2
                    .Either<_i5.Failure, _i10.ForecastWeather3HourModel>>.value(
                _FakeEither_0<_i5.Failure, _i10.ForecastWeather3HourModel>(
              this,
              Invocation.method(
                #getForecastFiveDaysWeather,
                [
                  lat,
                  lng,
                ],
              ),
            )),
            returnValueForMissingStub: _i9.Future<
                    _i2
                    .Either<_i5.Failure, _i10.ForecastWeather3HourModel>>.value(
                _FakeEither_0<_i5.Failure, _i10.ForecastWeather3HourModel>(
              this,
              Invocation.method(
                #getForecastFiveDaysWeather,
                [
                  lat,
                  lng,
                ],
              ),
            )),
          ) as _i9
              .Future<_i2.Either<_i5.Failure, _i10.ForecastWeather3HourModel>>);
}

/// A class which mocks [MyLocationLocalDataSourceImpl].
///
/// See the documentation for Mockito's code generation for more information.
class MockMyLocationLocalDataSourceImpl extends _i1.Mock
    implements _i11.MyLocationLocalDataSourceImpl {
  @override
  _i3.SharedPreferences get sharedPreferences => (super.noSuchMethod(
        Invocation.getter(#sharedPreferences),
        returnValue: _FakeSharedPreferences_1(
          this,
          Invocation.getter(#sharedPreferences),
        ),
        returnValueForMissingStub: _FakeSharedPreferences_1(
          this,
          Invocation.getter(#sharedPreferences),
        ),
      ) as _i3.SharedPreferences);

  @override
  _i2.Either<_i5.Failure, _i9.Future<bool>> addLocation(
          _i12.MyLocationEntity? place) =>
      (super.noSuchMethod(
        Invocation.method(
          #addLocation,
          [place],
        ),
        returnValue: _FakeEither_0<_i5.Failure, _i9.Future<bool>>(
          this,
          Invocation.method(
            #addLocation,
            [place],
          ),
        ),
        returnValueForMissingStub: _FakeEither_0<_i5.Failure, _i9.Future<bool>>(
          this,
          Invocation.method(
            #addLocation,
            [place],
          ),
        ),
      ) as _i2.Either<_i5.Failure, _i9.Future<bool>>);

  @override
  _i2.Either<_i5.Failure, List<_i12.MyLocationEntity>> getLocation() =>
      (super.noSuchMethod(
        Invocation.method(
          #getLocation,
          [],
        ),
        returnValue: _FakeEither_0<_i5.Failure, List<_i12.MyLocationEntity>>(
          this,
          Invocation.method(
            #getLocation,
            [],
          ),
        ),
        returnValueForMissingStub:
            _FakeEither_0<_i5.Failure, List<_i12.MyLocationEntity>>(
          this,
          Invocation.method(
            #getLocation,
            [],
          ),
        ),
      ) as _i2.Either<_i5.Failure, List<_i12.MyLocationEntity>>);

  @override
  _i2.Either<_i5.Failure, _i9.Future<bool>> removeLocation(
          _i12.MyLocationEntity? place) =>
      (super.noSuchMethod(
        Invocation.method(
          #removeLocation,
          [place],
        ),
        returnValue: _FakeEither_0<_i5.Failure, _i9.Future<bool>>(
          this,
          Invocation.method(
            #removeLocation,
            [place],
          ),
        ),
        returnValueForMissingStub: _FakeEither_0<_i5.Failure, _i9.Future<bool>>(
          this,
          Invocation.method(
            #removeLocation,
            [place],
          ),
        ),
      ) as _i2.Either<_i5.Failure, _i9.Future<bool>>);
}

/// A class which mocks [InjectableModule].
///
/// See the documentation for Mockito's code generation for more information.
class MockInjectableModule extends _i1.Mock implements _i13.InjectableModule {
  @override
  _i9.Future<_i3.SharedPreferences> get prefs => (super.noSuchMethod(
        Invocation.getter(#prefs),
        returnValue:
            _i9.Future<_i3.SharedPreferences>.value(_FakeSharedPreferences_1(
          this,
          Invocation.getter(#prefs),
        )),
        returnValueForMissingStub:
            _i9.Future<_i3.SharedPreferences>.value(_FakeSharedPreferences_1(
          this,
          Invocation.getter(#prefs),
        )),
      ) as _i9.Future<_i3.SharedPreferences>);

  @override
  _i4.InternetConnection get internetConnectionChecker => (super.noSuchMethod(
        Invocation.getter(#internetConnectionChecker),
        returnValue: _FakeInternetConnection_2(
          this,
          Invocation.getter(#internetConnectionChecker),
        ),
        returnValueForMissingStub: _FakeInternetConnection_2(
          this,
          Invocation.getter(#internetConnectionChecker),
        ),
      ) as _i4.InternetConnection);

  @override
  String get baseUrl => (super.noSuchMethod(
        Invocation.getter(#baseUrl),
        returnValue: _i14.dummyValue<String>(
          this,
          Invocation.getter(#baseUrl),
        ),
        returnValueForMissingStub: _i14.dummyValue<String>(
          this,
          Invocation.getter(#baseUrl),
        ),
      ) as String);

  @override
  String get apiKey => (super.noSuchMethod(
        Invocation.getter(#apiKey),
        returnValue: _i14.dummyValue<String>(
          this,
          Invocation.getter(#apiKey),
        ),
        returnValueForMissingStub: _i14.dummyValue<String>(
          this,
          Invocation.getter(#apiKey),
        ),
      ) as String);

  @override
  _i5.UrlBuilder get urlBuilder => (super.noSuchMethod(
        Invocation.getter(#urlBuilder),
        returnValue: _FakeUrlBuilder_3(
          this,
          Invocation.getter(#urlBuilder),
        ),
        returnValueForMissingStub: _FakeUrlBuilder_3(
          this,
          Invocation.getter(#urlBuilder),
        ),
      ) as _i5.UrlBuilder);

  @override
  _i6.EventBus get eventBus => (super.noSuchMethod(
        Invocation.getter(#eventBus),
        returnValue: _FakeEventBus_4(
          this,
          Invocation.getter(#eventBus),
        ),
        returnValueForMissingStub: _FakeEventBus_4(
          this,
          Invocation.getter(#eventBus),
        ),
      ) as _i6.EventBus);

  @override
  _i9.Future<_i7.Dio> get authenticatedDio => (super.noSuchMethod(
        Invocation.getter(#authenticatedDio),
        returnValue: _i9.Future<_i7.Dio>.value(_FakeDio_5(
          this,
          Invocation.getter(#authenticatedDio),
        )),
        returnValueForMissingStub: _i9.Future<_i7.Dio>.value(_FakeDio_5(
          this,
          Invocation.getter(#authenticatedDio),
        )),
      ) as _i9.Future<_i7.Dio>);
}

/// A class which mocks [Dio].
///
/// See the documentation for Mockito's code generation for more information.
class MockDio extends _i1.Mock implements _i7.Dio {
  @override
  _i7.BaseOptions get options => (super.noSuchMethod(
        Invocation.getter(#options),
        returnValue: _FakeBaseOptions_6(
          this,
          Invocation.getter(#options),
        ),
        returnValueForMissingStub: _FakeBaseOptions_6(
          this,
          Invocation.getter(#options),
        ),
      ) as _i7.BaseOptions);

  @override
  set options(_i7.BaseOptions? _options) => super.noSuchMethod(
        Invocation.setter(
          #options,
          _options,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i7.HttpClientAdapter get httpClientAdapter => (super.noSuchMethod(
        Invocation.getter(#httpClientAdapter),
        returnValue: _FakeHttpClientAdapter_7(
          this,
          Invocation.getter(#httpClientAdapter),
        ),
        returnValueForMissingStub: _FakeHttpClientAdapter_7(
          this,
          Invocation.getter(#httpClientAdapter),
        ),
      ) as _i7.HttpClientAdapter);

  @override
  set httpClientAdapter(_i7.HttpClientAdapter? _httpClientAdapter) =>
      super.noSuchMethod(
        Invocation.setter(
          #httpClientAdapter,
          _httpClientAdapter,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i7.Transformer get transformer => (super.noSuchMethod(
        Invocation.getter(#transformer),
        returnValue: _FakeTransformer_8(
          this,
          Invocation.getter(#transformer),
        ),
        returnValueForMissingStub: _FakeTransformer_8(
          this,
          Invocation.getter(#transformer),
        ),
      ) as _i7.Transformer);

  @override
  set transformer(_i7.Transformer? _transformer) => super.noSuchMethod(
        Invocation.setter(
          #transformer,
          _transformer,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i7.Interceptors get interceptors => (super.noSuchMethod(
        Invocation.getter(#interceptors),
        returnValue: _FakeInterceptors_9(
          this,
          Invocation.getter(#interceptors),
        ),
        returnValueForMissingStub: _FakeInterceptors_9(
          this,
          Invocation.getter(#interceptors),
        ),
      ) as _i7.Interceptors);

  @override
  void close({bool? force = false}) => super.noSuchMethod(
        Invocation.method(
          #close,
          [],
          {#force: force},
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i9.Future<_i7.Response<T>> get<T>(
    String? path, {
    Map<String, dynamic>? queryParameters,
    _i7.Options? options,
    _i7.CancelToken? cancelToken,
    _i7.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #get,
          [path],
          {
            #queryParameters: queryParameters,
            #options: options,
            #cancelToken: cancelToken,
            #onReceiveProgress: onReceiveProgress,
          },
        ),
        returnValue: _i9.Future<_i7.Response<T>>.value(_FakeResponse_10<T>(
          this,
          Invocation.method(
            #get,
            [path],
            {
              #queryParameters: queryParameters,
              #options: options,
              #cancelToken: cancelToken,
              #onReceiveProgress: onReceiveProgress,
            },
          ),
        )),
        returnValueForMissingStub:
            _i9.Future<_i7.Response<T>>.value(_FakeResponse_10<T>(
          this,
          Invocation.method(
            #get,
            [path],
            {
              #queryParameters: queryParameters,
              #options: options,
              #cancelToken: cancelToken,
              #onReceiveProgress: onReceiveProgress,
            },
          ),
        )),
      ) as _i9.Future<_i7.Response<T>>);

  @override
  _i9.Future<_i7.Response<T>> getUri<T>(
    Uri? uri, {
    _i7.Options? options,
    _i7.CancelToken? cancelToken,
    _i7.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getUri,
          [uri],
          {
            #options: options,
            #cancelToken: cancelToken,
            #onReceiveProgress: onReceiveProgress,
          },
        ),
        returnValue: _i9.Future<_i7.Response<T>>.value(_FakeResponse_10<T>(
          this,
          Invocation.method(
            #getUri,
            [uri],
            {
              #options: options,
              #cancelToken: cancelToken,
              #onReceiveProgress: onReceiveProgress,
            },
          ),
        )),
        returnValueForMissingStub:
            _i9.Future<_i7.Response<T>>.value(_FakeResponse_10<T>(
          this,
          Invocation.method(
            #getUri,
            [uri],
            {
              #options: options,
              #cancelToken: cancelToken,
              #onReceiveProgress: onReceiveProgress,
            },
          ),
        )),
      ) as _i9.Future<_i7.Response<T>>);

  @override
  _i9.Future<_i7.Response<T>> post<T>(
    String? path, {
    dynamic data,
    Map<String, dynamic>? queryParameters,
    _i7.Options? options,
    _i7.CancelToken? cancelToken,
    _i7.ProgressCallback? onSendProgress,
    _i7.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #post,
          [path],
          {
            #data: data,
            #queryParameters: queryParameters,
            #options: options,
            #cancelToken: cancelToken,
            #onSendProgress: onSendProgress,
            #onReceiveProgress: onReceiveProgress,
          },
        ),
        returnValue: _i9.Future<_i7.Response<T>>.value(_FakeResponse_10<T>(
          this,
          Invocation.method(
            #post,
            [path],
            {
              #data: data,
              #queryParameters: queryParameters,
              #options: options,
              #cancelToken: cancelToken,
              #onSendProgress: onSendProgress,
              #onReceiveProgress: onReceiveProgress,
            },
          ),
        )),
        returnValueForMissingStub:
            _i9.Future<_i7.Response<T>>.value(_FakeResponse_10<T>(
          this,
          Invocation.method(
            #post,
            [path],
            {
              #data: data,
              #queryParameters: queryParameters,
              #options: options,
              #cancelToken: cancelToken,
              #onSendProgress: onSendProgress,
              #onReceiveProgress: onReceiveProgress,
            },
          ),
        )),
      ) as _i9.Future<_i7.Response<T>>);

  @override
  _i9.Future<_i7.Response<T>> postUri<T>(
    Uri? uri, {
    dynamic data,
    _i7.Options? options,
    _i7.CancelToken? cancelToken,
    _i7.ProgressCallback? onSendProgress,
    _i7.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #postUri,
          [uri],
          {
            #data: data,
            #options: options,
            #cancelToken: cancelToken,
            #onSendProgress: onSendProgress,
            #onReceiveProgress: onReceiveProgress,
          },
        ),
        returnValue: _i9.Future<_i7.Response<T>>.value(_FakeResponse_10<T>(
          this,
          Invocation.method(
            #postUri,
            [uri],
            {
              #data: data,
              #options: options,
              #cancelToken: cancelToken,
              #onSendProgress: onSendProgress,
              #onReceiveProgress: onReceiveProgress,
            },
          ),
        )),
        returnValueForMissingStub:
            _i9.Future<_i7.Response<T>>.value(_FakeResponse_10<T>(
          this,
          Invocation.method(
            #postUri,
            [uri],
            {
              #data: data,
              #options: options,
              #cancelToken: cancelToken,
              #onSendProgress: onSendProgress,
              #onReceiveProgress: onReceiveProgress,
            },
          ),
        )),
      ) as _i9.Future<_i7.Response<T>>);

  @override
  _i9.Future<_i7.Response<T>> put<T>(
    String? path, {
    dynamic data,
    Map<String, dynamic>? queryParameters,
    _i7.Options? options,
    _i7.CancelToken? cancelToken,
    _i7.ProgressCallback? onSendProgress,
    _i7.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #put,
          [path],
          {
            #data: data,
            #queryParameters: queryParameters,
            #options: options,
            #cancelToken: cancelToken,
            #onSendProgress: onSendProgress,
            #onReceiveProgress: onReceiveProgress,
          },
        ),
        returnValue: _i9.Future<_i7.Response<T>>.value(_FakeResponse_10<T>(
          this,
          Invocation.method(
            #put,
            [path],
            {
              #data: data,
              #queryParameters: queryParameters,
              #options: options,
              #cancelToken: cancelToken,
              #onSendProgress: onSendProgress,
              #onReceiveProgress: onReceiveProgress,
            },
          ),
        )),
        returnValueForMissingStub:
            _i9.Future<_i7.Response<T>>.value(_FakeResponse_10<T>(
          this,
          Invocation.method(
            #put,
            [path],
            {
              #data: data,
              #queryParameters: queryParameters,
              #options: options,
              #cancelToken: cancelToken,
              #onSendProgress: onSendProgress,
              #onReceiveProgress: onReceiveProgress,
            },
          ),
        )),
      ) as _i9.Future<_i7.Response<T>>);

  @override
  _i9.Future<_i7.Response<T>> putUri<T>(
    Uri? uri, {
    dynamic data,
    _i7.Options? options,
    _i7.CancelToken? cancelToken,
    _i7.ProgressCallback? onSendProgress,
    _i7.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #putUri,
          [uri],
          {
            #data: data,
            #options: options,
            #cancelToken: cancelToken,
            #onSendProgress: onSendProgress,
            #onReceiveProgress: onReceiveProgress,
          },
        ),
        returnValue: _i9.Future<_i7.Response<T>>.value(_FakeResponse_10<T>(
          this,
          Invocation.method(
            #putUri,
            [uri],
            {
              #data: data,
              #options: options,
              #cancelToken: cancelToken,
              #onSendProgress: onSendProgress,
              #onReceiveProgress: onReceiveProgress,
            },
          ),
        )),
        returnValueForMissingStub:
            _i9.Future<_i7.Response<T>>.value(_FakeResponse_10<T>(
          this,
          Invocation.method(
            #putUri,
            [uri],
            {
              #data: data,
              #options: options,
              #cancelToken: cancelToken,
              #onSendProgress: onSendProgress,
              #onReceiveProgress: onReceiveProgress,
            },
          ),
        )),
      ) as _i9.Future<_i7.Response<T>>);

  @override
  _i9.Future<_i7.Response<T>> head<T>(
    String? path, {
    dynamic data,
    Map<String, dynamic>? queryParameters,
    _i7.Options? options,
    _i7.CancelToken? cancelToken,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #head,
          [path],
          {
            #data: data,
            #queryParameters: queryParameters,
            #options: options,
            #cancelToken: cancelToken,
          },
        ),
        returnValue: _i9.Future<_i7.Response<T>>.value(_FakeResponse_10<T>(
          this,
          Invocation.method(
            #head,
            [path],
            {
              #data: data,
              #queryParameters: queryParameters,
              #options: options,
              #cancelToken: cancelToken,
            },
          ),
        )),
        returnValueForMissingStub:
            _i9.Future<_i7.Response<T>>.value(_FakeResponse_10<T>(
          this,
          Invocation.method(
            #head,
            [path],
            {
              #data: data,
              #queryParameters: queryParameters,
              #options: options,
              #cancelToken: cancelToken,
            },
          ),
        )),
      ) as _i9.Future<_i7.Response<T>>);

  @override
  _i9.Future<_i7.Response<T>> headUri<T>(
    Uri? uri, {
    dynamic data,
    _i7.Options? options,
    _i7.CancelToken? cancelToken,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #headUri,
          [uri],
          {
            #data: data,
            #options: options,
            #cancelToken: cancelToken,
          },
        ),
        returnValue: _i9.Future<_i7.Response<T>>.value(_FakeResponse_10<T>(
          this,
          Invocation.method(
            #headUri,
            [uri],
            {
              #data: data,
              #options: options,
              #cancelToken: cancelToken,
            },
          ),
        )),
        returnValueForMissingStub:
            _i9.Future<_i7.Response<T>>.value(_FakeResponse_10<T>(
          this,
          Invocation.method(
            #headUri,
            [uri],
            {
              #data: data,
              #options: options,
              #cancelToken: cancelToken,
            },
          ),
        )),
      ) as _i9.Future<_i7.Response<T>>);

  @override
  _i9.Future<_i7.Response<T>> delete<T>(
    String? path, {
    dynamic data,
    Map<String, dynamic>? queryParameters,
    _i7.Options? options,
    _i7.CancelToken? cancelToken,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #delete,
          [path],
          {
            #data: data,
            #queryParameters: queryParameters,
            #options: options,
            #cancelToken: cancelToken,
          },
        ),
        returnValue: _i9.Future<_i7.Response<T>>.value(_FakeResponse_10<T>(
          this,
          Invocation.method(
            #delete,
            [path],
            {
              #data: data,
              #queryParameters: queryParameters,
              #options: options,
              #cancelToken: cancelToken,
            },
          ),
        )),
        returnValueForMissingStub:
            _i9.Future<_i7.Response<T>>.value(_FakeResponse_10<T>(
          this,
          Invocation.method(
            #delete,
            [path],
            {
              #data: data,
              #queryParameters: queryParameters,
              #options: options,
              #cancelToken: cancelToken,
            },
          ),
        )),
      ) as _i9.Future<_i7.Response<T>>);

  @override
  _i9.Future<_i7.Response<T>> deleteUri<T>(
    Uri? uri, {
    dynamic data,
    _i7.Options? options,
    _i7.CancelToken? cancelToken,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteUri,
          [uri],
          {
            #data: data,
            #options: options,
            #cancelToken: cancelToken,
          },
        ),
        returnValue: _i9.Future<_i7.Response<T>>.value(_FakeResponse_10<T>(
          this,
          Invocation.method(
            #deleteUri,
            [uri],
            {
              #data: data,
              #options: options,
              #cancelToken: cancelToken,
            },
          ),
        )),
        returnValueForMissingStub:
            _i9.Future<_i7.Response<T>>.value(_FakeResponse_10<T>(
          this,
          Invocation.method(
            #deleteUri,
            [uri],
            {
              #data: data,
              #options: options,
              #cancelToken: cancelToken,
            },
          ),
        )),
      ) as _i9.Future<_i7.Response<T>>);

  @override
  _i9.Future<_i7.Response<T>> patch<T>(
    String? path, {
    dynamic data,
    Map<String, dynamic>? queryParameters,
    _i7.Options? options,
    _i7.CancelToken? cancelToken,
    _i7.ProgressCallback? onSendProgress,
    _i7.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #patch,
          [path],
          {
            #data: data,
            #queryParameters: queryParameters,
            #options: options,
            #cancelToken: cancelToken,
            #onSendProgress: onSendProgress,
            #onReceiveProgress: onReceiveProgress,
          },
        ),
        returnValue: _i9.Future<_i7.Response<T>>.value(_FakeResponse_10<T>(
          this,
          Invocation.method(
            #patch,
            [path],
            {
              #data: data,
              #queryParameters: queryParameters,
              #options: options,
              #cancelToken: cancelToken,
              #onSendProgress: onSendProgress,
              #onReceiveProgress: onReceiveProgress,
            },
          ),
        )),
        returnValueForMissingStub:
            _i9.Future<_i7.Response<T>>.value(_FakeResponse_10<T>(
          this,
          Invocation.method(
            #patch,
            [path],
            {
              #data: data,
              #queryParameters: queryParameters,
              #options: options,
              #cancelToken: cancelToken,
              #onSendProgress: onSendProgress,
              #onReceiveProgress: onReceiveProgress,
            },
          ),
        )),
      ) as _i9.Future<_i7.Response<T>>);

  @override
  _i9.Future<_i7.Response<T>> patchUri<T>(
    Uri? uri, {
    dynamic data,
    _i7.Options? options,
    _i7.CancelToken? cancelToken,
    _i7.ProgressCallback? onSendProgress,
    _i7.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #patchUri,
          [uri],
          {
            #data: data,
            #options: options,
            #cancelToken: cancelToken,
            #onSendProgress: onSendProgress,
            #onReceiveProgress: onReceiveProgress,
          },
        ),
        returnValue: _i9.Future<_i7.Response<T>>.value(_FakeResponse_10<T>(
          this,
          Invocation.method(
            #patchUri,
            [uri],
            {
              #data: data,
              #options: options,
              #cancelToken: cancelToken,
              #onSendProgress: onSendProgress,
              #onReceiveProgress: onReceiveProgress,
            },
          ),
        )),
        returnValueForMissingStub:
            _i9.Future<_i7.Response<T>>.value(_FakeResponse_10<T>(
          this,
          Invocation.method(
            #patchUri,
            [uri],
            {
              #data: data,
              #options: options,
              #cancelToken: cancelToken,
              #onSendProgress: onSendProgress,
              #onReceiveProgress: onReceiveProgress,
            },
          ),
        )),
      ) as _i9.Future<_i7.Response<T>>);

  @override
  void lock() => super.noSuchMethod(
        Invocation.method(
          #lock,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void unlock() => super.noSuchMethod(
        Invocation.method(
          #unlock,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void clear() => super.noSuchMethod(
        Invocation.method(
          #clear,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i9.Future<_i7.Response<dynamic>> download(
    String? urlPath,
    dynamic savePath, {
    _i7.ProgressCallback? onReceiveProgress,
    Map<String, dynamic>? queryParameters,
    _i7.CancelToken? cancelToken,
    bool? deleteOnError = true,
    String? lengthHeader = r'content-length',
    dynamic data,
    _i7.Options? options,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #download,
          [
            urlPath,
            savePath,
          ],
          {
            #onReceiveProgress: onReceiveProgress,
            #queryParameters: queryParameters,
            #cancelToken: cancelToken,
            #deleteOnError: deleteOnError,
            #lengthHeader: lengthHeader,
            #data: data,
            #options: options,
          },
        ),
        returnValue:
            _i9.Future<_i7.Response<dynamic>>.value(_FakeResponse_10<dynamic>(
          this,
          Invocation.method(
            #download,
            [
              urlPath,
              savePath,
            ],
            {
              #onReceiveProgress: onReceiveProgress,
              #queryParameters: queryParameters,
              #cancelToken: cancelToken,
              #deleteOnError: deleteOnError,
              #lengthHeader: lengthHeader,
              #data: data,
              #options: options,
            },
          ),
        )),
        returnValueForMissingStub:
            _i9.Future<_i7.Response<dynamic>>.value(_FakeResponse_10<dynamic>(
          this,
          Invocation.method(
            #download,
            [
              urlPath,
              savePath,
            ],
            {
              #onReceiveProgress: onReceiveProgress,
              #queryParameters: queryParameters,
              #cancelToken: cancelToken,
              #deleteOnError: deleteOnError,
              #lengthHeader: lengthHeader,
              #data: data,
              #options: options,
            },
          ),
        )),
      ) as _i9.Future<_i7.Response<dynamic>>);

  @override
  _i9.Future<_i7.Response<dynamic>> downloadUri(
    Uri? uri,
    dynamic savePath, {
    _i7.ProgressCallback? onReceiveProgress,
    _i7.CancelToken? cancelToken,
    bool? deleteOnError = true,
    String? lengthHeader = r'content-length',
    dynamic data,
    _i7.Options? options,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #downloadUri,
          [
            uri,
            savePath,
          ],
          {
            #onReceiveProgress: onReceiveProgress,
            #cancelToken: cancelToken,
            #deleteOnError: deleteOnError,
            #lengthHeader: lengthHeader,
            #data: data,
            #options: options,
          },
        ),
        returnValue:
            _i9.Future<_i7.Response<dynamic>>.value(_FakeResponse_10<dynamic>(
          this,
          Invocation.method(
            #downloadUri,
            [
              uri,
              savePath,
            ],
            {
              #onReceiveProgress: onReceiveProgress,
              #cancelToken: cancelToken,
              #deleteOnError: deleteOnError,
              #lengthHeader: lengthHeader,
              #data: data,
              #options: options,
            },
          ),
        )),
        returnValueForMissingStub:
            _i9.Future<_i7.Response<dynamic>>.value(_FakeResponse_10<dynamic>(
          this,
          Invocation.method(
            #downloadUri,
            [
              uri,
              savePath,
            ],
            {
              #onReceiveProgress: onReceiveProgress,
              #cancelToken: cancelToken,
              #deleteOnError: deleteOnError,
              #lengthHeader: lengthHeader,
              #data: data,
              #options: options,
            },
          ),
        )),
      ) as _i9.Future<_i7.Response<dynamic>>);

  @override
  _i9.Future<_i7.Response<T>> request<T>(
    String? path, {
    dynamic data,
    Map<String, dynamic>? queryParameters,
    _i7.CancelToken? cancelToken,
    _i7.Options? options,
    _i7.ProgressCallback? onSendProgress,
    _i7.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #request,
          [path],
          {
            #data: data,
            #queryParameters: queryParameters,
            #cancelToken: cancelToken,
            #options: options,
            #onSendProgress: onSendProgress,
            #onReceiveProgress: onReceiveProgress,
          },
        ),
        returnValue: _i9.Future<_i7.Response<T>>.value(_FakeResponse_10<T>(
          this,
          Invocation.method(
            #request,
            [path],
            {
              #data: data,
              #queryParameters: queryParameters,
              #cancelToken: cancelToken,
              #options: options,
              #onSendProgress: onSendProgress,
              #onReceiveProgress: onReceiveProgress,
            },
          ),
        )),
        returnValueForMissingStub:
            _i9.Future<_i7.Response<T>>.value(_FakeResponse_10<T>(
          this,
          Invocation.method(
            #request,
            [path],
            {
              #data: data,
              #queryParameters: queryParameters,
              #cancelToken: cancelToken,
              #options: options,
              #onSendProgress: onSendProgress,
              #onReceiveProgress: onReceiveProgress,
            },
          ),
        )),
      ) as _i9.Future<_i7.Response<T>>);

  @override
  _i9.Future<_i7.Response<T>> requestUri<T>(
    Uri? uri, {
    dynamic data,
    _i7.CancelToken? cancelToken,
    _i7.Options? options,
    _i7.ProgressCallback? onSendProgress,
    _i7.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #requestUri,
          [uri],
          {
            #data: data,
            #cancelToken: cancelToken,
            #options: options,
            #onSendProgress: onSendProgress,
            #onReceiveProgress: onReceiveProgress,
          },
        ),
        returnValue: _i9.Future<_i7.Response<T>>.value(_FakeResponse_10<T>(
          this,
          Invocation.method(
            #requestUri,
            [uri],
            {
              #data: data,
              #cancelToken: cancelToken,
              #options: options,
              #onSendProgress: onSendProgress,
              #onReceiveProgress: onReceiveProgress,
            },
          ),
        )),
        returnValueForMissingStub:
            _i9.Future<_i7.Response<T>>.value(_FakeResponse_10<T>(
          this,
          Invocation.method(
            #requestUri,
            [uri],
            {
              #data: data,
              #cancelToken: cancelToken,
              #options: options,
              #onSendProgress: onSendProgress,
              #onReceiveProgress: onReceiveProgress,
            },
          ),
        )),
      ) as _i9.Future<_i7.Response<T>>);

  @override
  _i9.Future<_i7.Response<T>> fetch<T>(_i7.RequestOptions? requestOptions) =>
      (super.noSuchMethod(
        Invocation.method(
          #fetch,
          [requestOptions],
        ),
        returnValue: _i9.Future<_i7.Response<T>>.value(_FakeResponse_10<T>(
          this,
          Invocation.method(
            #fetch,
            [requestOptions],
          ),
        )),
        returnValueForMissingStub:
            _i9.Future<_i7.Response<T>>.value(_FakeResponse_10<T>(
          this,
          Invocation.method(
            #fetch,
            [requestOptions],
          ),
        )),
      ) as _i9.Future<_i7.Response<T>>);
}

/// A class which mocks [SharedPreferences].
///
/// See the documentation for Mockito's code generation for more information.
class MockSharedPreferences extends _i1.Mock implements _i3.SharedPreferences {
  @override
  Set<String> getKeys() => (super.noSuchMethod(
        Invocation.method(
          #getKeys,
          [],
        ),
        returnValue: <String>{},
        returnValueForMissingStub: <String>{},
      ) as Set<String>);

  @override
  Object? get(String? key) => (super.noSuchMethod(
        Invocation.method(
          #get,
          [key],
        ),
        returnValueForMissingStub: null,
      ) as Object?);

  @override
  bool? getBool(String? key) => (super.noSuchMethod(
        Invocation.method(
          #getBool,
          [key],
        ),
        returnValueForMissingStub: null,
      ) as bool?);

  @override
  int? getInt(String? key) => (super.noSuchMethod(
        Invocation.method(
          #getInt,
          [key],
        ),
        returnValueForMissingStub: null,
      ) as int?);

  @override
  double? getDouble(String? key) => (super.noSuchMethod(
        Invocation.method(
          #getDouble,
          [key],
        ),
        returnValueForMissingStub: null,
      ) as double?);

  @override
  String? getString(String? key) => (super.noSuchMethod(
        Invocation.method(
          #getString,
          [key],
        ),
        returnValueForMissingStub: null,
      ) as String?);

  @override
  bool containsKey(String? key) => (super.noSuchMethod(
        Invocation.method(
          #containsKey,
          [key],
        ),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  List<String>? getStringList(String? key) => (super.noSuchMethod(
        Invocation.method(
          #getStringList,
          [key],
        ),
        returnValueForMissingStub: null,
      ) as List<String>?);

  @override
  _i9.Future<bool> setBool(
    String? key,
    bool? value,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #setBool,
          [
            key,
            value,
          ],
        ),
        returnValue: _i9.Future<bool>.value(false),
        returnValueForMissingStub: _i9.Future<bool>.value(false),
      ) as _i9.Future<bool>);

  @override
  _i9.Future<bool> setInt(
    String? key,
    int? value,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #setInt,
          [
            key,
            value,
          ],
        ),
        returnValue: _i9.Future<bool>.value(false),
        returnValueForMissingStub: _i9.Future<bool>.value(false),
      ) as _i9.Future<bool>);

  @override
  _i9.Future<bool> setDouble(
    String? key,
    double? value,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #setDouble,
          [
            key,
            value,
          ],
        ),
        returnValue: _i9.Future<bool>.value(false),
        returnValueForMissingStub: _i9.Future<bool>.value(false),
      ) as _i9.Future<bool>);

  @override
  _i9.Future<bool> setString(
    String? key,
    String? value,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #setString,
          [
            key,
            value,
          ],
        ),
        returnValue: _i9.Future<bool>.value(false),
        returnValueForMissingStub: _i9.Future<bool>.value(false),
      ) as _i9.Future<bool>);

  @override
  _i9.Future<bool> setStringList(
    String? key,
    List<String>? value,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #setStringList,
          [
            key,
            value,
          ],
        ),
        returnValue: _i9.Future<bool>.value(false),
        returnValueForMissingStub: _i9.Future<bool>.value(false),
      ) as _i9.Future<bool>);

  @override
  _i9.Future<bool> remove(String? key) => (super.noSuchMethod(
        Invocation.method(
          #remove,
          [key],
        ),
        returnValue: _i9.Future<bool>.value(false),
        returnValueForMissingStub: _i9.Future<bool>.value(false),
      ) as _i9.Future<bool>);

  @override
  _i9.Future<bool> commit() => (super.noSuchMethod(
        Invocation.method(
          #commit,
          [],
        ),
        returnValue: _i9.Future<bool>.value(false),
        returnValueForMissingStub: _i9.Future<bool>.value(false),
      ) as _i9.Future<bool>);

  @override
  _i9.Future<bool> clear() => (super.noSuchMethod(
        Invocation.method(
          #clear,
          [],
        ),
        returnValue: _i9.Future<bool>.value(false),
        returnValueForMissingStub: _i9.Future<bool>.value(false),
      ) as _i9.Future<bool>);

  @override
  _i9.Future<void> reload() => (super.noSuchMethod(
        Invocation.method(
          #reload,
          [],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);
}
